title: Lifx Ambilight Addon for Kodi
description: Kodi add-on for Lifx lights with ambilight support.
# @Todo: Revert temp Fix for GA4. See https://github.com/pages-themes/cayman/issues/161
google_analytics: G-ZKDNXYBJTK
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
